//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAppSqlDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApplication2201802_dbEntities : DbContext
    {
        public WebApplication2201802_dbEntities()
            : base("name=WebApplication2201802_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tag_Profile> Tag_Profile { get; set; }
        public virtual DbSet<Visitor_Photo> Visitor_Photo { get; set; }
        public virtual DbSet<Visitor_Profile> Visitor_Profile { get; set; }
    }
}
