//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTABLE
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int AGE { get; set; }
        public string Arrived { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public System.DateTime CreateAt { get; set; }
        public long TagID { get; set; }
    }
}
