//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTRegistApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_Profile
    {
        public int ID { get; set; }
        public string VisitorId { get; set; }
        public string VisitorName { get; set; }
        public string VisitorCompany { get; set; }
        public string Arrived { get; set; }
        public System.DateTime VisitTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long NFCid { get; set; }
    }
}
