//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTRegistApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Visitor_Detail
    {
        public int Id { get; set; }
        public int VisitorId { get; set; }
        public string VisitorName { get; set; }
        public string VisitorCompany { get; set; }
        public string Arrived { get; set; }
        public Nullable<DateTime> VisitTime { get; set; }
        public int EventID { get; set; }
        public string PhotoUrl { get; set; }
    }
}
