//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTRegistApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Registration_dbEntities : DbContext
    {
        public Registration_dbEntities()
            : base("name=Registration_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tag_Profile> Tag_Profile { get; set; }
        public virtual DbSet<Visitors_Profile> Visitors_Profile { get; set; }
        public virtual DbSet<Visitors_Photo> Visitors_Photo { get; set; }
        public virtual DbSet<Event_Profile> Event_Profile { get; set; }
        public virtual DbSet<History_Visitor_Detail> History_Visitor_Detail { get; set; }
    }
}
