//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTRegistApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitors_Photo
    {
        public int PhotoId { get; set; }
        public string PhotoName { get; set; }
        public string PhotoUrl { get; set; }
        public int VisitorId { get; set; }
    }
}
